# Use an official Node.js runtime as a base image
FROM node:20

# Set the working directory in the container
WORKDIR /home/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the application code to the working directory
COPY . .

# Use ts-node-dev for development
CMD ["npm", "run", "dev"]
